import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, render, screen, fireEvent } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'
import { GardenRepository } from './domain/repository'

afterEach(() => { cleanup(); localStorage.clear(); vi.restoreAllMocks() })
function setup() {
  const repository = new GardenRepository(localStorage)
  repository.clearDemoData()
  return repository
}
it('offers one capture field and opens the captured idea without advanced controls', async () => {
  const user = userEvent.setup(); const repository = setup()
  render(<App repository={repository} />)
  expect(screen.getByRole('heading', { name: 'What do you want to move forward?' })).toBeInTheDocument()
  expect(screen.getAllByRole('textbox')).toHaveLength(1)
  expect(screen.queryByLabelText('Energy')).not.toBeInTheDocument()
  await user.type(screen.getByLabelText('New idea'), 'Prepare for an interview')
  await user.click(screen.getByRole('button', { name: 'Add idea' }))
  expect(screen.getByRole('heading', { name: 'Prepare for an interview' })).toBeInTheDocument()
  expect(repository.getState().seeds[0].text).toBe('Prepare for an interview')
})
it('keeps the next action and records progress in the same detail view', async () => {
  const user = userEvent.setup(); const repository = setup()
  repository.captureSeed({ text: 'Prepare for an interview' })
  render(<App repository={repository} />)
  await user.click(screen.getByRole('button', { name: /Open Prepare for an interview/ }))
  await user.click(screen.getByRole('button', { name: 'Edit idea' }))
  await user.type(screen.getByLabelText('Next action'), 'Practice one debugging story')
  await user.click(screen.getByRole('button', { name: 'Save idea' }))
  await user.click(screen.getByRole('button', { name: 'Start focus' }))
  expect(screen.getByText('Practice one debugging story')).toBeInTheDocument()
  await user.type(screen.getByLabelText('What changed?'), 'Drafted a clear explanation of the fix.')
  await user.click(screen.getByRole('button', { name: 'Save progress' }))
  expect(screen.getByText('Drafted a clear explanation of the fix.')).toBeInTheDocument()
  expect(repository.getState().focusSessions[0].status).toBe('completed')
  await user.click(screen.getByRole('button', { name: 'AI handoff' }))
  expect((screen.getByLabelText('Handoff preview') as HTMLTextAreaElement).value).toContain('Drafted a clear explanation of the fix.')
})
it('finds archived work and restores it without losing its next action', async () => {
  const user = userEvent.setup(); const repository = setup()
  const seed = repository.captureSeed({ text: 'Interview story' })
  repository.editSeed(seed.id, { text: seed.text, note: '', nextAction: 'Practice debugging' })
  render(<App repository={repository} />)
  await user.click(screen.getByRole('button', { name: /Open Interview story/ }))
  await user.click(screen.getByRole('button', { name: 'Archive idea' }))
  expect(screen.queryByRole('button', { name: /Open Interview story/ })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Search' }))
  await user.type(screen.getByLabelText('Search ideas'), 'debugging')
  await user.click(screen.getByRole('button', { name: /Open Interview story/ }))
  await user.click(screen.getByRole('button', { name: 'Restore idea' }))
  expect(repository.getState().seeds[0].status).not.toBe('archived')
  expect(repository.getState().seeds[0].nextAction).toBe('Practice debugging')
})
it('preserves a capture draft when storage rejects a write', async () => {
  const user = userEvent.setup(); const repository = setup()
  render(<App repository={repository} />)
  vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Storage full') })
  await user.type(screen.getByLabelText('New idea'), 'Keep my draft')
  await user.click(screen.getByRole('button', { name: 'Add idea' }))
  expect(screen.getByRole('alert')).toHaveTextContent('Storage full')
  expect(screen.getByLabelText('New idea')).toHaveValue('Keep my draft')
  expect(repository.getState().seeds).toHaveLength(0)
})
it('invalidates changed import previews and requires confirmation to replace data', async () => {
  const user = userEvent.setup(); const repository = setup()
  repository.captureSeed({ text: 'Keep this' }); const backup = repository.exportData()
  render(<App repository={repository} />)
  await user.click(screen.getByRole('button', { name: 'Settings' }))
  fireEvent.change(screen.getByLabelText('Import JSON'), { target: { value: backup } })
  await user.click(screen.getByRole('button', { name: 'Preview import' }))
  expect(screen.getByRole('button', { name: 'Replace local data' })).toBeInTheDocument()
  await user.type(screen.getByLabelText('Import JSON'), ' ')
  expect(screen.queryByRole('button', { name: 'Replace local data' })).not.toBeInTheDocument()
  await user.click(screen.getByRole('button', { name: 'Preview import' }))
  vi.spyOn(window, 'confirm').mockReturnValue(false)
  await user.click(screen.getByRole('button', { name: 'Replace local data' }))
  expect(repository.getState().seeds[0].text).toBe('Keep this')
})
it('resumes saved work after reload with its next action and draft outcome intact', async () => {
  const user = userEvent.setup(); const repository = setup()
  const seed = repository.captureSeed({ text: 'Ship a thoughtful portfolio' })
  repository.editSeed(seed.id, { text: seed.text, note: 'Show engineering decisions', nextAction: 'Write the migration story' })
  repository.startFocusSession(seed.id, 15)
  const session = repository.getActiveFocusSession()!
  repository.setFocusOutcome(session.id, 'Outlined the data compatibility checks')
  repository.pauseFocusSession(session.id)
  const reloaded = new GardenRepository(localStorage)
  render(<App repository={reloaded} />)
  await user.click(screen.getByRole('button', { name: /Open Ship a thoughtful portfolio/ }))
  expect(screen.getByText('Write the migration story')).toBeInTheDocument()
  expect(screen.getByLabelText('What changed?')).toHaveValue('Outlined the data compatibility checks')
  await user.click(screen.getByRole('button', { name: 'Resume' }))
  expect(reloaded.getActiveFocusSession()?.status).toBe('running')
  await user.click(screen.getByRole('button', { name: 'Save progress' }))
  expect(reloaded.getState().focusSessions[0].outcome).toBe('Outlined the data compatibility checks')
})
